environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

install:
  - "python --version"

build_script:
  - "python -m pip install ."

test_script:
  - "python -m unittest discover -v"
