language: python
# Each attribute in the matrix will override the global attribute.
matrix:
  include:
    - os: linux
      - python: 2.6
        env: LANG=C
      - python: 2.7
    - os: osx
install:
  - pip install .
script:
  - python test_subprocess32.py
# Python 2.6 does not have test discovery.
#  - python -m unittest discover
