language: python
os: linux
# Each attribute in the matrix will override the global attribute.
matrix:
  include:
    - python: 2.6
    - python: 2.7
    - os: osx
install:
  - pip install .
script:
  - python test_subprocess32.py
# Python 2.6 does not have test discovery.
#  - python -m unittest discover
